export enum authActionTypes {
SIGN_UP_WITHOUT_PASSWORD_REQUEST = '@auth/SIGN_UP_WITHOUT_PASSWORD_REQUEST',
SIGN_UP_WITHOUT_PASSWORD_FAILURE = '@auth/SIGN_UP_WITHOUT_PASSWORD_FAILURE',
SIGN_UP_WITHOUT_PASSWORD_SUCCESS = '@auth/SIGN_UP_WITHOUT_PASSWORD_SUCCESS',
};
